### ISSUE TITLE
Bunny.Save() bug

### ISSUE THREAD

**Issue by julianje** [julianje/Bunny#19]
>>> Bunny.Save(Experiment,"Test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Bunny/BunnyFunctions.py", line 93, in Save
    pickle.dump(Exp,open(Filename, "wb"))
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 1370, in dump
    Pickler(file, protocol).dump(obj)
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 600, in save_list
    self._batch_appends(iter(obj))
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 615, in _batch_appends
    save(x)
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/julianjara-ettinger/anaconda/lib/python2.7/pickle.py", line 748, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <function F at 0x1056c9050>: it's not found as Bunny.ParticipantLibrary.F
>>>

**Comment by julianje** [comment]
Postpone for version 2.0
