### ISSUE TITLE
TTest did something weird when connecting with empirical distribution

### ISSUE THREAD

**Issue by julianje** [julianje/Bunny#27]
>>> Test = Bunny.DataTest(Bunny.TestLibrary.TTest())
>>> 
>>> Experiment = Bunny.Experiment([Effort,NoEffort],Test,"Baby effort experiment")
>>> 
>>> Bunny.Explore(Experiment)
/Users/julianjara-ettinger/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py:83: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/Users/julianjara-ettinger/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py:117: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/Users/julianjara-ettinger/anaconda/lib/python2.7/site-packages/scipy/stats/stats.py:3107: RuntimeWarning: invalid value encountered in absolute
  prob = distributions.t.sf(np.abs(t), df) * 2  # use np.abs to get upper tail
Exploring sample sizes ... 
No limit specified. Testing samples between 15 and 35 ...
Estimating time ....
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Bunny/BunnyFunctions.py", line 14, in Explore
    res = ExploreSampleSize(Exp)
  File "Bunny/BunnyFunctions.py", line 148, in ExploreSampleSize
    Power.append(Exp.GetPower(samples))
  File "Bunny/Experiment.py", line 55, in GetPower
    return sum(results)*1.0/len(results)
TypeError: unsupported operand type(s) for +: 'int' and 'list'
>>>

**Comment by julianje** [comment]
Fixed errors in DataTest library
